#!/bin/sh

set -o errexit

if [ $# = 0 ]
then
  echo "ERROR - Syntax: $0 filename"
  echo "    Lines in file must look like         username:pwd"
  echo "    Using database table USR attributes  USR_LOGIN:USR_PASSWORD"
  echo
  exit 80
fi

. ./setenv.sh

cf="at/agoracon/oim/Crypto"
cj="at.agoracon.oim.Crypto"

# compile
if [ ! -f "classes/${cf}.class" ] || \
   [ "classes/${cf}.class" -ot "src/${cf}.java" ]
then
  echo "Compiling classes..."
  [ -d classes ] || mkdir -p classes
  javac -d classes "src/${cf}.java"
  echo "Compilation finished"
fi

# run
echo "Starting program. Please be patient, Java is slow..."
cat $1 | \
java -DDOMAIN_HOME=${DOMAIN_HOME} \
  -DOIM_HOME=${ORACLE_HOME}/server \
  -Doracle.security.jps.config=${DOMAIN_HOME}/config/fmwconfig/jps-config-jse.xml \
  -DXL.HomeDir=/${DOMAIN_HOME}/config/fmwconfig \
  -DJAVA_HOME=${JAVA_HOME} \
  -DkeyStoreFileName=.xldatabasekey \
  ${cj}

# vi:ft=sh:
