#!/bin/sh

set -o errexit

. ./setenv.sh

cj="at.agoracon.oim.Crypto"


cf=${cj//\./\/}
if [ ! -f "classes/${cf}.class" ] || \
   [ "classes/${cf}.class" -ot "src/${cf}.java" ]
then
  echo "Compiling classes..." >&2
  [ -d classes ] || mkdir -p classes
  javac -d classes "src/${cf}.java"
  echo "Compilation finished" >&2
fi

echo "Slowly starting stack. Be patient..." >&2

java -DDOMAIN_HOME=${DOMAIN_HOME} \
  -DOIM_HOME=${ORACLE_HOME}/server \
  -Doracle.security.jps.config=${DOMAIN_HOME}/config/fmwconfig/jps-config-jse.xml \
  -DXL.HomeDir=${DOMAIN_HOME}/config/fmwconfig \
  -DkeyStoreFileName=.xldatabasekey \
  ${cj} $*

# vi:ft=sh:
